### ISSUE TITLE
Erreur pendant la migration

### ISSUE THREAD

**Issue by Its-Alex** [stephane-klein/postgresql-pgtap-graphile-migrate-skeleton#2]
En executant la migration je me retrouve avec une erreur:

```bash
➜  postgresql-pgtap-graphile-migrate-skeleton git:(main) pnpm run migrate:commit

> my-app@0.0.1 migrate:commit /home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton
> graphile-migrate commit

graphile-migrate[shadow]: dropped database 'myapp_shadow'
graphile-migrate[shadow]: recreated database 'myapp_shadow'
graphile-migrate[shadow]: Running migration '000001.sql'
graphile-migrate[shadow]: 1 committed migrations executed
graphile-migrate: New migration '000002.sql' created
graphile-migrate[shadow]: Running migration '000002.sql'
graphile-migrate[shadow]: 1 committed migrations executed
graphile-migrate: Running migration '000002.sql'

🛑 Error occurred whilst processing migration
    error: column "name" does not exist
        at /home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Object.runQueryWithErrorInstrumentation (/home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/instrumentation.js:8:26)
        at async /home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/migration.js:242:13
        at async Object.withAdvisoryLock (/home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/pgReal.js:115:16)
        at async Object.runCommittedMigration (/home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/migration.js:288:5)
        at async /home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/commands/migrate.js:27:17
        at async Object.withAdvisoryLock (/home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/pgReal.js:115:16)
        at async /home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/commands/migrate.js:18:9
        at async Object.withClient (/home/alexandre.marre/Documents/postgresql-pgtap-graphile-migrate-skeleton/node_modules/.pnpm/graphile-migrate@1.4.1/node_modules/graphile-migrate/dist/pgReal.js:92:20)

    Severity:   ERROR
    Code:       42703

ABORTING...
ABORTED AND ROLLED BACK
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by stephane-klein** [comment]
J'arrive bien à reproduire le problème :+1:.

**Comment by stephane-klein** [comment]
@Its-Alex chez moi, c'est fixé avec https://github.com/stephane-klein/postgresql-pgtap-graphile-migrate-skeleton/commit/3561e65049e06ca8e987e628b44ce74785b8de1d

Est-ce que c'est bon pour toi ?

**Comment by Its-Alex** [comment]
@stephane-klein Oui c'est bon chez moi :+1:
